In [1]:
import pandas as pd
import os

In [4]:
df = pd.read_csv('../nifty500_enp.csv')

In [5]:
df.head()

,Unnamed: 0,Company Name,Industry,Symbol,eps,bv,insider_h,inst_h,float_pc,price,dv_avg,trn_avg
0,0,3M India Ltd.,CONSUMER GOODS,3MINDIA,144.140,1695.911,76.480,8.921000,0.229404,26391.400391,-0.001125,2.321755e+07
1,1,ABB India Ltd.,INDUSTRIAL MANUFACTURING,ABB,13.960,170.186,75.000,14.151000,0.247490,1495.650024,-0.000750,1.216263e+08
2,2,ABB Power Products and Systems India Ltd.,INDUSTRIAL MANUFACTURING,POWERINDIA,25.976,220.029,77.024,11.006000,0.241460,1806.250000,-0.000853,6.708751e+07
3,3,ACC Ltd.,CEMENT & CEMENT PRODUCTS,ACC,88.701,676.251,57.144,28.893998,0.426041,1961.199951,-0.000657,6.413141e+08
4,4,AIA Engineering Ltd.,INDUSTRIAL MANUFACTURING,AIAENG,60.020,449.929,58.557,33.188000,0.314692,1943.150024,-0.000498,5.489719e+07

In [6]:
df['PE'] = df['price'] / df['eps']
df['PB'] = df['price']/df['bv']